const mongoose = require("mongoose")

mongoose.connect(process.env.MONGODB_URI,{
    dbName:process.env.DB_NAME, 
    useNewUrlParser: true ,
    useUnifiedTopology: true ,
    useFindAndModify:false,
    useCreateIndex:true})
.then(()=>{
    console.log("DB connected")
})
.catch(err=>console.log(err.message))

mongoose.connection.on('connected',()=>{
    console.log("mongoose connectedd to DB")
})

mongoose.connection.on('err',(err)=>{
    console.log(err.message)
    
})
mongoose.connection.on('disconnected',()=>{
    console.log('mongoose connection is disconnected')
})

//SIGINT is generated by the user pressing Ctrl + C and is an interrupt. SIGTERM is a signal that is sent to request the process terminates

process.on('SIGINT',async()=>{
    await mongoose.connection.close();
    process.exit(0);
})